apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: orderly
data:
  nginx.conf: |
    user nginx;
    worker_processes 1;
    events {
        worker_connections 1024;
    }
    http {
        default_type application/octet-stream;  
              
        server {
            listen 80;
            
            location /api/ {
                proxy_pass http://kong-service:8000/;
                proxy_set_header Host              $http_host;
                proxy_set_header X-Real-IP         $remote_addr;
                proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
            location /kong/config/ {
                proxy_pass http://kong-service:8001/;      
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_hide_header X-Powered-By;
                proxy_set_header Host $http_host;
                proxy_set_header X-Forwarded-Proto $scheme;    
            }
            error_page 404 /404.html;            
        }
    }