apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: orderly
data:
  nginx.conf: |
    user nginx;
    worker_processes 1;
    events {
        worker_connections 1024;
    }
    http {
        default_type application/octet-stream;  
              
        server {
            listen 80;
            
            location /api/ {
                proxy_pass http://kong-service:8000/;
            }

            location /kong/config/ {
                proxy_pass http://kong-service:8001/;        
            }

            location /auth/ {
                proxy_pass ${SERVERLESS_FUNCTION_ENDPOINT};
                proxy_set_header Authorization "${GCLOUD_AUTH}";
                proxy_set_header Content-Type "application/json";
            }
            
            error_page 404 /404.html;            
        }
    }