apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: orderly
spec:
  type: NodePort
  selector:
    app: nginx # Seletor para selecionar os pods do NGINX
  ports:
  - protocol: TCP
    port: 80 # Porta do serviço exposto
    targetPort: 80 # Porta em que o NGINX está ouvindo dentro do pod
    nodePort: 30000
