apiVersion: v1
kind: ConfigMap
metadata:
  name: broker-configmap
  namespace: orderly
data:
  RABBITMQ_ERLANG_COOKIE: TRIBUFUSTACK
  RABBITMQ_DEFAULT_USER: "${BROKER_USER}" # admin
  RABBITMQ_DEFAULT_PASS: "${BROKER_PASSWORD}" # admin
