apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong-deployment
  namespace: orderly
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong-deployment
  template:
    metadata:
      labels:
        app: kong-deployment
    spec:
      automountServiceAccountToken: false
      containers:
      - name: kong-container
        image: kong:3.3.1-alpine
        ports:
        - containerPort: 8000
        - containerPort: 8001
        - containerPort: 8443
        - containerPort: 8444
        env:
        - name: KONG_DATABASE
          value: "off"
        - name: KONG_DECLARATIVE_CONFIG
          value: "/tmp/kong-config.yml"
        - name: KONG_PROXY_ACCESS_LOG
          value: "/dev/stdout"
        - name: KONG_ADMIN_ACCESS_LOG
          value: "/dev/stdout"
        - name: KONG_PROXY_ERROR_LOG
          value: "/dev/stderr"
        - name: KONG_ADMIN_ERROR_LOG
          value: "/dev/stderr"
        - name: KONG_ADMIN_LISTEN
          value: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
        - name: KONG_PROXY_LISTEN
          value: "0.0.0.0:8000, 0.0.0.0:8443 ssl"
        - name: KONG_LOG_LEVEL
          value: "debug"
        - name: KONG_PLUGINS
          value: "bundled"
        volumeMounts:
        - name: kong-config-volume
          mountPath: /tmp/kong-config.yml
          subPath: kong-config.yml
      volumes:
      - name: kong-config-volume
        configMap:
          name: kong-configmap
