apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: orderly
data:
  nginx.conf: |
    user nginx;
    worker_processes 1;
    events {
        worker_connections 1024;
    }
    http {
        default_type application/octet-stream; 
        server_tokens off; 
        upstream kong-api-gateway {
            server kong-service:8000;
        }
        upstream rabbitmq {
            least_conn;
            server broker-service-controlpanel:15672 weight=10 max_fails=3 fail_timeout=30s;
        }  
        upstream financial-api {
            server ms-financial-service:3003;
        }
        upstream auth-api {
            server ms-auth-service:3000;
        }
        server {
            listen 80;
            location /rabbitmq/api/ {
                rewrite ^ $request_uri;
                rewrite ^/rabbitmq/api/(.*) /api/$1 break;
                return 400;
                proxy_pass http://rabbitmq$uri;
            }
            location /rabbitmq {
                rewrite ^/rabbitmq$ /rabbitmq/ permanent;
                rewrite ^/rabbitmq/(.*)$ /$1 break;
                proxy_pass http://rabbitmq;
                proxy_buffering                    off;
                proxy_set_header Host              $http_host;
                proxy_set_header X-Real-IP         $remote_addr;
                proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
            location /api/ {    
                proxy_pass http://kong-api-gateway/;         
            }
            location /financial/ {
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_hide_header X-Powered-By;
                proxy_set_header Host $http_host;
                proxy_set_header X-Forwarded-Proto $scheme;    
                proxy_pass http://financial-api/;         
            }
            location /auth/ {
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_hide_header X-Powered-By;
                proxy_set_header Host $http_host;
                proxy_set_header X-Forwarded-Proto $scheme;    
                proxy_pass http://ms-auth-service:3000/;         
            }
            location /kong/config/ {
                proxy_pass http://kong-service:8001/;        
            }
            error_page 404 /404.html;            
        }
    }