apiVersion: v1
kind: ConfigMap
metadata:
  name: db-configmap
  namespace: orderly
data:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: postgres
  PGDATA: /data/postgresql/orderly
