apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache-deployment
spec:
  selector:
    matchLabels:
      app: cache
  replicas: 1
  template:
    metadata:
      labels:
        app: cache
    spec:
      containers:
      - name: cache-container
        image: redis:7.0.8-alpine
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        envFrom:
        - configMapRef:
            name: cache-configmap
        ports:
        - containerPort: 6379
        startupProbe:
          tcpSocket:
            port: 6379
          periodSeconds: 5
          failureThreshold: 30
        readinessProbe:
          tcpSocket:
            port: 6379
          periodSeconds: 3
          failureThreshold: 3
        livenessProbe:
          tcpSocket:
            port: 6379
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
