name: Apply

on: [push, workflow_dispatch]

jobs:
  apply:
    runs-on: ubuntu-latest
    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CRED }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Auth GCloud
        uses: 'google-github-actions/auth@v2.1.2'
        with:
            credentials_json: ${{ secrets.GOOGLE_CRED }}
            export_environment_variables: true
            create_credentials_file: true
      
      - id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GOOGLE_CRED }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      # - name: Activate Service Account on Google Cloud
        # run: gcloud auth activate-service-account --key-file=${{ secrets.GOOGLE_CRED }}

      - name: Setup Cluster Kubernetes
        run: gcloud container clusters get-credentials ${{ vars.CLUSTER }} --region ${{ vars.REGION }} --project ${{ vars.PROJECT }}


      - name: Setup Kubernetes
        run: gcloud container clusters get-credentials ${{ vars.CLUSTER }} --region ${{ vars.REGION }} --project ${{ vars.PROJECT }}
    
      - name: Setup Namespace
        run: |
            kubectl apply -f namespaces.yaml
            kubectl config set-context --current --namespace=orderly

      - name: Apply Redis
        working-directory: redis/
        run: kubectl apply -f k8s/

      - name: Apply Database
        working-directory: postgres/
        run: kubectl apply -f k8s/

      - name: Apply API
        working-directory: orderly-api/
        run: kubectl apply -f k8s/
      
      - name: Apply API Gateway
        working-directory: kong/
        run: kubectl apply -f k8s/

      - name: Apply Nginx
        working-directory: nginx/
        run: kubectl apply -f k8s/