name: Destroy

on: [workflow_dispatch]

jobs:
  destroy:
    runs-on: ubuntu-latest
    env:
      GOOGLE_CREDENTIALS: ${{ secrets.CREDENTIALS }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Auth GCloud
        uses: 'google-github-actions/auth@v2.1.2'
        with:
            credentials_json: ${{ secrets.CREDENTIALS }}
            export_environment_variables: true
            create_credentials_file: true

      - name: Setup Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Setup Cluster Kubernetes
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
          cluster_name: ${{ vars.CLUSTER_NAME }}
          location: ${{ vars.ZONE }}

      - name: Setup Namespace
        run: kubectl config set-context --current --namespace=orderly   

      - name: delete nginx
        working-directory: nginx/
        run: kubectl delete -f k8s/

      - name: delete API gateway
        working-directory: kong/
        run: kubectl delete -f k8s/

      - name: delete db
        working-directory: postgres/
        run: kubectl delete -f k8s/

      - name: delete redis
        working-directory: redis/
        run: kubectl delete -f k8s/

      - name: delete namespace
        run: kubectl delete -f namespaces.yaml


      
